#定义步骤
kind: pipeline
name: default


services:
- name: database
  image: mysql
  environment:
    MYSQL_DATABASE: feedback
    MYSQL_USER: ymx
    MYSQL_PASSWORD: 123
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

- name: my-image
  image: registry.cn-hangzhou.aliyuncs.com/web-ci/nginx-build:v1
  commands:
    - ls
    - cd /etc/nginx/
    - ls
    - cat -n /etc/nginx/nginx.conf
    - cd /etc/nginx/sites-enabled
    - ls
    - cat /etc/nginx/sites-enabled/default
    - nginx -t
    - nginx
    - service nginx status
    - curl http://www.baidu.com
# steps:
#   - name: vue-install test-unit test-e2e
#     image: cypress/included:3.2.0
#     commands:
#       - ls
#       - cd /
#       - ls
#       - curl http://localhost
#       - curl http://www.baidu.com
#       - cd resources/vue
#       - npm install  #--registry https://registry.npm.taobao.org
#       - npm run test:unit
#       - npm run startOnCI

#   - name: vueBuild
#     image: node
#     commands:
#       - ls
#       - cd /
#       - ls
#       - cd /var
#       - ls
#       - cd resources/vue
#       - npm install  #--registry https://registry.npm.taobao.org
#       - npm run build
